### ISSUE TITLE
Use session data to send users surveys

### ISSUE THREAD

**Issue by eliasyishak** [eliasyishak/dash_analytics#1]
If a user has analytics enabled and they have not been active on any dash tools, send some kind of survey to understand why, while also highlighting other tooling they may not know about.

**Comment by eliasyishak** [comment]
FYI @anderdobo

**Comment by anderdobo** [comment]
FYI @jayoung-lee for tracking in relation to contextual in-IDE survey initiative.

**Comment by eliasyishak** [comment]
This is also related to https://github.com/eliasyishak/dash_analytics/issues/4 – we will need to first persist data locally before creating APIs for accessing insights from the persisted data

**Comment by eliasyishak** [comment]
Clients of this package (Dash related tools) have access to an API on the `Analytics` class that will allow them to query the persisted logs using the example shown below

```dart

final Analytics analytics = Analytics(...);

final LogFileStats? query = analytics.logFileStats();
```

Note that the query variable is nullable – the result can be null for several reasons, such as; no data persisted, data is malformed, etc. So users of this api should properly check before calling methods to share a survey with users.
