### ISSUE TITLE
Singleton with setup vs Constructor

### ISSUE THREAD

**Issue by eliasyishak** [eliasyishak/dash_analytics#2]
Moving our conversation @christopherfujino from the commit to an issue to track better.

The original comment on commit on the `lib/src/analytics.dart` file: https://github.com/eliasyishak/dash_analytics/commit/595be88c0f94423e26cbec2c7ffd15964ae19341#diff-8959a2a24fd89be63385a1feffed84beb3be8dab70ec527a4d3dcafc938607f6

Current setup
```dart
// Setup the singleton
Analytics.setup(...);

// Can call the singleton like this after
// within different classes, files, etc.
final Analytics analytics = Analytics();
final Analytics analytics2 = Analytics();
```

If we don't want to use a setup static method before calling for the singleton, we will need to change the design of the package so that the analytics singleton is initialized once and passed down to children where analytics events are passed.

With the current setup we can setup once at the entry point and easily import the package's `Analytics` class anywhere within the codebase so long as the setup has happened before.

**Comment by christopherfujino** [comment]
It's not clear to me that this:

```dart
Analytics.setup(...);

void func1() => Analytics().sendEvent(...);
void func2() => Analytics().sendEvent(...);
```

is better than:

```dart
final Analytics globalAnalytics = Analytics(...);

void func1() => globalAnalytics.sendEvent(...);
void func2() => globalAnalytics.sendEvent(...);
```

And with the latter there isn't the risk of a runtime error after a code refactor (if you use it wrong, it would be statically detected).

**Comment by eliasyishak** [comment]
This is more of what I was thinking in the context of sending events related to run times, but I believe this can be applied to events where we send hit counts (how many times we call a function), error reporting, etc.

```dart
void main() {

  // Calling this at the entry point will ensure that
  // calling for the singleton with the default constructor
  // will work
  Analytics.setup(...);

  final Child child = Child();
  child.run();
}

// This class doesn't actually need to make any analytics related
// calls so it doesn't need to read in or call for the singleton
class Child {
  Child();

  void run() {
    final GrandChild grandChild = grandChild();
    grandChild.runProcessWithAnalytics();
  }
}

// This is the class that we want to run send analytics from
class GrandChild {
  final Analytics analytics; // **REFACTOR**
  GrandChild() : analytics = Analytics(); // **REFACTOR**

  void runProcessWithAnalytics() {
    final DateTime start = DateTime.now();
    // Some code here to run

    // This could be how long `runProcessWithAnalytics` takes to run for example
    final int millisecondsRun = DateTime.now().difference(start).inMilliseconds
    analytics.sendEvent(millisecondsRun, ...);
  }
}
```

With this approach there would be less refactoring because I don't need to pass the analytics singleton class from the entry point where it was initialized down to the `GrandChild` class to send the event, it can just be called for when the `GrandChild` is being created with the default constructor.

In the context of `flutter-tools` we can initialize this class near the entry point and maybe send it to globals where it can be referenced, but I didn't want to assume other dash tooling had a globals-like configuration; I also thought we wanted to move away from adding more to globals.

If this is not desirable, then we can change to this approach below, I just wanted to illustrate what I was thinking when designing the approach for this package.

```dart
void main() {

  // We can delete the `setup` constructor and have all logic
  // handled within the default constructor for setup
  final Analytics globalAnalytics = Analytics(...);

  final Child child = Child(analytics=globalAnalytics); // **REFACTOR**
  child.run();
}

// This class doesn't actually need to make any analytics related
// calls but it needs to have the analytics class fed to it so it can
// pass it to the GrandChild class
class Child {
  final Analytics analytics; // **REFACTOR**
  Child({required analytics}); // **REFACTOR**

  void run() {
    final GrandChild grandChild = grandChild(analytics=analytics); // **REFACTOR**
    grandChild.runProcessWithAnalytics();
  }
}

// This is the class that we want to run send analytics from
class GrandChild {
  final Analytics analytics; // **REFACTOR** (same as first example)
  GrandChild({required analytics}); // **REFACTOR** (same as first example)

  void runProcessWithAnalytics() {
    final DateTime start = DateTime.now();
    // Some code here to run

    // This could be how long `runProcessWithAnalytics` takes to run for example
    final int millisecondsRun = DateTime.now().difference(start).inMilliseconds
    analytics.sendEvent(millisecondsRun, ...);
  }
}
```

So in the above examples, the first had 2 refactor points, while the second had 6, which I would expect to be significantly more in actual production code with far more nested children classes.

**Comment by christopherfujino** [comment]
Your second example above could be written:

```
final Analytics globalAnalytics = Analytics(...);

void main() {
  final Child child = Child();
  child.run();
}

class Child {
  Child();

  void run() {
    final GrandChild grandChild = grandChild();
    grandChild.runProcessWithAnalytics();
  }
}

class GrandChild {
  GrandChild();

  void runProcessWithAnalytics() {
    final DateTime start = DateTime.now();
    // Some code here to run

    globalAnalytics.sendEvent(millisecondsRun, ...);
  }
}
```

I'm not saying that we should do it this way (I would prefer explicit direct injection, which is what https://github.com/flutter/flutter/issues/47161 is all about), but I'm saying this would avoid an explicit call to `Analytics.setup()`, and referencing the global variable `globalAnalytics` is roughly equivalent to calling a factory constructor that really only returns a singleton. If that singleton requires explicit setup, why use a factory that makes the user **think** they're constructing their own local instance?

> In the context of flutter-tools we can initialize this class near the entry point and maybe send it to globals where it can be referenced, but I didn't want to assume other dash tooling had a globals-like configuration;

The first approach above (the way commit https://github.com/eliasyishak/dash_analytics/commit/595be88c0f94423e26cbec2c7ffd15964ae19341 is currently written) is essentially grabbing a global value that tests can't override anyway, so they it would be roughly equivalent to just make it a global variable--no special setup needed.

> I also thought we wanted to move away from adding more to globals.

We are never going to avoid having global values, what we are trying to avoid is using context.get() in favor of direct injection because it forces a developer writing tests to know about and provide dependencies in their tests, where they can explicitly provide hermetic versions. The problem we're trying to avoid is non-obvious calls to global values.

**Comment by eliasyishak** [comment]
Hmm that's a great point, I do like having the class getting setup in the global scope so it would be very easy to reference it within different classes in different files. Let me refactor and open a new PR. I like your approach

**Comment by eliasyishak** [comment]
Closing after approval on https://github.com/eliasyishak/dash_analytics/pull/3
