### ISSUE TITLE
Parameters for the base `Analytics(...)` class

### ISSUE THREAD

**Issue by eliasyishak** [eliasyishak/dash_analytics#24]
Discussion from @bwilkerson

The class `Analytics` takes several pieces of data, and the example has (presumably) fake values for these. How will I know what the correct values are for these parameters when using the package in production? I could imagine an enum for the `tool` name, and I think I can figure out how to find the Dart and Flutter version numbers (though if there's a standard way we might want to consider computing them in the analytics package rather than making every client duplicate the code), but it seems like we wouldn't want some of the data to be visible in the source code (like `measurementId` and `apiSecret`).

**Comment by eliasyishak** [comment]
This is a great question. At the moment, we haven't decided on what information should be passed into the `Analytics` class and what should be resolved by the package itself. We may still have things like the flutter and dart versions get resolved within the package but moving the `meaurementId` and `apiSecret` may involve some more discussion because this package is going to get published to pub.dev so we may not want anyone that can `pub get` this package to be able to send events to GA

**Comment by bwilkerson** [comment]
> ... we haven't decided on what information should be passed into the `Analytics` class ...

I'm guessing that that's something that needs to happen before we publish the package.

> ... we may not want anyone that can pub get this package to be able to send events to GA

I'd say that was guaranteed to be true. It would be exceedingly bad if someone else could send analytics to our account. They could corrupt the data, launch a DOS attack, or worst of all could send PII.

I'll be interested to hear how we can publish open source code without making the keys public.

**Comment by eliasyishak** [comment]
Because this package will be used across various dash related tools, we may need to initialize the instance of the `Analytics` class differently.  Snippet is below shows how the instance gets initialized with dummy values for the parameters
```dart
final Analytics analytics = Analytics(
  tool: DashTool.flutterTools,
  measurementId: measurementId,
  apiSecret: apiSecret,
  flutterChannel: 'ey-test-channel',
  flutterVersion: 'Flutter 3.6.0-7.0.pre.47',
  dartVersion: 'Dart 2.19.0',
);
```

However, a developer could potentially only use dart on their machine, and would not have anything flutter related. In that case, there would be no way of providing a value for `flutterChannel` and `flutterVersion` so these parameters should be labeled as nullable. And any tests, methods, etc. that depend on all of these values should also be refactored for these nullable values
